package co.za.task.tracker.util.constants;

public enum AppConstant {
    BEAR,
    AUTHORIZATION,
    JWT_SECRET,
    JWT_EXPIRATION_TIME,
    BAD_EMAIL_FORMAT,
    EMAIL_EXISTS,
    WENT_WRONG_MESSAGE,
    NO_DATA_MESSAGE,
    NO_DOCUMENTS,
    SUCCESS_DELETE_MESSAGE,
    SAVE_SUCCESS_MESSAGE,
    UNAUTHORIZED_MESSAGE,
    BAD_LOGIN_CREDENTIALS,
    HTTP_HEAD,
    HTTP_OPTIONS,
    HTTP_GET,
    HTTP_POST,
    HTTP_PUT,
    HTTP_PATCH,
    HTTP_DELETE,
    FE_BASE_DOMAIN
}
